pipeline:
    name: Canaryk8
    identifier: Canaryk8
    projectIdentifier: CSETest1
    orgIdentifier: orglijo
    tags: {}
    stages:
        - stage:
              name: canarydeploy
              identifier: canarydeploy
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: canarysrv
                      serviceDefinition:
                          spec:
                              variables: []
                              manifests:
                                  - manifest:
                                        identifier: nginx
                                        type: K8sManifest
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: account.harnessgitconnector
                                                    gitFetchType: Branch
                                                    paths:
                                                        - content/en/examples/application/nginx-app.yaml
                                                    repoName: website
                                                    branch: main
                                            skipResourceVersioning: false
                          type: Kubernetes
                  infrastructure:
                      environmentRef: canaryenv
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: k8testcluster
                              namespace: default
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - stepGroup:
                                name: Canary Deployment
                                identifier: canaryDepoyment
                                steps:
                                    - step:
                                          name: Canary Deployment
                                          identifier: canaryDeployment
                                          type: K8sCanaryDeploy
                                          timeout: 10m
                                          spec:
                                              instanceSelection:
                                                  spec:
                                                      percentage: 50
                                                  type: Percentage
                                              skipDryRun: false
                                    - step:
                                          type: HarnessApproval
                                          name: approval before canary delete
                                          identifier: approval_before_canary_delete
                                          spec:
                                              approvalMessage: Please review the following information and approve the pipeline progression
                                              includePipelineExecutionHistory: true
                                              approvers:
                                                  userGroups:
                                                      - account.testusergroup
                                                  minimumCount: 1
                                                  disallowPipelineExecutor: false
                                              approverInputs: []
                                          timeout: 1d
                                    - step:
                                          name: Canary Delete
                                          identifier: canaryDelete
                                          type: K8sCanaryDelete
                                          timeout: 10m
                                          spec:
                                              skipDryRun: false
                                          failureStrategies: []
                          - step:
                                type: HarnessApproval
                                name: approval after canary delete
                                identifier: approval_after_canary_delete
                                spec:
                                    approvalMessage: Please review the following information and approve the pipeline progression
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        userGroups:
                                            - account.testusergroup
                                        minimumCount: 1
                                        disallowPipelineExecutor: false
                                    approverInputs: []
                                timeout: 1d
                          - stepGroup:
                                name: Primary Deployment
                                identifier: primaryDepoyment
                                steps:
                                    - step:
                                          name: Rolling Deployment
                                          identifier: rollingDeployment
                                          type: K8sRollingDeploy
                                          timeout: 10m
                                          spec:
                                              skipDryRun: false
                      rollbackSteps:
                          - step:
                                name: Canary Delete
                                identifier: rollbackCanaryDelete
                                type: K8sCanaryDelete
                                timeout: 10m
                                spec: {}
                          - step:
                                name: Rolling Rollback
                                identifier: rollingRollback
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
