pipeline:
    name: k8helm
    identifier: k8helm
    projectIdentifier: CSETest1
    orgIdentifier: orglijo
    tags: {}
    stages:
        - stage:
              name: Helmdeploy
              identifier: Helmdeploy
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: k8shelmservice
                      serviceDefinition:
                          spec:
                              variables: []
                              manifests:
                                  - manifest:
                                        identifier: chart
                                        type: HelmChart
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: account.harnessgitconnector
                                                    gitFetchType: Branch
                                                    folderPath: "charts/buildachart "
                                                    repoName: " my-helm-charts"
                                                    branch: main
                                            skipResourceVersioning: false
                                            helmVersion: V3
                          type: Kubernetes
                  infrastructure:
                      environmentRef: K8bgEnv
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: k8testcluster
                              namespace: bg
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
