pipeline:
    name: RD1
    identifier: RD1
    projectIdentifier: CSETest1
    orgIdentifier: orglijo
    tags: {}
    stages:
        - stage:
              name: RD1-stage
              identifier: RD1stage
              description: ""
              type: Deployment
              spec:
                  serviceConfig:
                      serviceRef: RD1SVC
                      serviceDefinition:
                          spec:
                              variables: []
                              manifests:
                                  - manifest:
                                        identifier: k8s-manifest
                                        type: K8sManifest
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: account.harnessgitconnector
                                                    gitFetchType: Branch
                                                    paths:
                                                        - deployment.yaml
                                                        - namespace.yaml
                                                        - service.yaml
                                                    repoName: test
                                                    branch: main
                                            skipResourceVersioning: false
                                  - manifest:
                                        identifier: values
                                        type: Values
                                        spec:
                                            store:
                                                type: Github
                                                spec:
                                                    connectorRef: account.harnessgitconnector
                                                    gitFetchType: Branch
                                                    paths:
                                                        - ng_values_dockercfg.yaml
                                                    repoName: test
                                                    branch: main
                          type: Kubernetes
                  infrastructure:
                      environmentRef: RD1ENV
                      infrastructureDefinition:
                          type: KubernetesDirect
                          spec:
                              connectorRef: k8testcluster
                              namespace: rv
                              releaseName: release-<+INFRA_KEY>
                      allowSimultaneousDeployments: false
                  execution:
                      steps:
                          - step:
                                name: Rollout Deployment
                                identifier: rolloutDeployment
                                type: K8sRollingDeploy
                                timeout: 10m
                                spec:
                                    skipDryRun: false
                                    delegateSelectors:
                                        - new-delegate-ng
                                failureStrategies: []
                      rollbackSteps:
                          - step:
                                name: Rollback Rollout Deployment
                                identifier: rollbackRolloutDeployment
                                type: K8sRollingRollback
                                timeout: 10m
                                spec: {}
              tags: {}
              failureStrategies:
                  - onFailure:
                        errors:
                            - AllErrors
                        action:
                            type: StageRollback
